syntax = "proto3";

package marks;
option go_package="generated-marks/;marksservice";

message CommentItem {
  string nickname = 1;
  string comment = 2;
}

message NewReq {
  string nickname = 1;
  string comment = 2;
  double latitude = 3;
  double longitude = 4;
  string request_trace = 5;
}
message NewRes {}

message GetReq {
  double latitude = 1;
  double longitude = 2;
  string request_trace = 3;
}
message GetRes {
  int32 total_reports = 1;
  repeated CommentItem comments = 2;
}

service MarksService {
  rpc New (NewReq) returns (NewRes);
  rpc Get (GetReq) returns (GetRes);
}
