syntax = "proto3";

package users;
option go_package="generated-users/;usersservice";

message RegReq {
  string nickname = 1;
  string password = 2;
  string request_trace = 3;
}
message RegRes {}

message LogReq {
  string nickname = 1;
  string password = 2;
  string request_trace = 3;
}
message LogRes {}

message DelReq {
  string nickname = 1;
  string request_trace = 2;
}
message DelRes {}

service UsersService {
  rpc Register (RegReq) returns (RegRes);
  rpc Login (LogReq) returns (LogRes);
  rpc Delete (DelReq) returns (DelRes);
}
