// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: marks.proto

package marksservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarksService_New_FullMethodName = "/marks.MarksService/New"
	MarksService_Get_FullMethodName = "/marks.MarksService/Get"
)

// MarksServiceClient is the client API for MarksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarksServiceClient interface {
	New(ctx context.Context, in *NewReq, opts ...grpc.CallOption) (*NewRes, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
}

type marksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarksServiceClient(cc grpc.ClientConnInterface) MarksServiceClient {
	return &marksServiceClient{cc}
}

func (c *marksServiceClient) New(ctx context.Context, in *NewReq, opts ...grpc.CallOption) (*NewRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewRes)
	err := c.cc.Invoke(ctx, MarksService_New_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marksServiceClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRes)
	err := c.cc.Invoke(ctx, MarksService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarksServiceServer is the server API for MarksService service.
// All implementations must embed UnimplementedMarksServiceServer
// for forward compatibility.
type MarksServiceServer interface {
	New(context.Context, *NewReq) (*NewRes, error)
	Get(context.Context, *GetReq) (*GetRes, error)
	mustEmbedUnimplementedMarksServiceServer()
}

// UnimplementedMarksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarksServiceServer struct{}

func (UnimplementedMarksServiceServer) New(context.Context, *NewReq) (*NewRes, error) {
	return nil, status.Error(codes.Unimplemented, "method New not implemented")
}
func (UnimplementedMarksServiceServer) Get(context.Context, *GetReq) (*GetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMarksServiceServer) mustEmbedUnimplementedMarksServiceServer() {}
func (UnimplementedMarksServiceServer) testEmbeddedByValue()                      {}

// UnsafeMarksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarksServiceServer will
// result in compilation errors.
type UnsafeMarksServiceServer interface {
	mustEmbedUnimplementedMarksServiceServer()
}

func RegisterMarksServiceServer(s grpc.ServiceRegistrar, srv MarksServiceServer) {
	// If the following call panics, it indicates UnimplementedMarksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarksService_ServiceDesc, srv)
}

func _MarksService_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarksServiceServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarksService_New_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarksServiceServer).New(ctx, req.(*NewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarksService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarksServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarksService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarksServiceServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MarksService_ServiceDesc is the grpc.ServiceDesc for MarksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marks.MarksService",
	HandlerType: (*MarksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _MarksService_New_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MarksService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marks.proto",
}
