// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: marks.proto

package marksservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_marks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_marks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_marks_proto_rawDescGZIP(), []int{0}
}

func (x *CommentItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommentItem) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type NewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewReq) Reset() {
	*x = NewReq{}
	mi := &file_marks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewReq) ProtoMessage() {}

func (x *NewReq) ProtoReflect() protoreflect.Message {
	mi := &file_marks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewReq.ProtoReflect.Descriptor instead.
func (*NewReq) Descriptor() ([]byte, []int) {
	return file_marks_proto_rawDescGZIP(), []int{1}
}

func (x *NewReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *NewReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *NewReq) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NewReq) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type NewRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRes) Reset() {
	*x = NewRes{}
	mi := &file_marks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRes) ProtoMessage() {}

func (x *NewRes) ProtoReflect() protoreflect.Message {
	mi := &file_marks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRes.ProtoReflect.Descriptor instead.
func (*NewRes) Descriptor() ([]byte, []int) {
	return file_marks_proto_rawDescGZIP(), []int{2}
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_marks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_marks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_marks_proto_rawDescGZIP(), []int{3}
}

func (x *GetReq) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetReq) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TotalReports  int32                  `protobuf:"varint,3,opt,name=total_reports,json=totalReports,proto3" json:"total_reports,omitempty"`
	Comments      []*CommentItem         `protobuf:"bytes,4,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_marks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_marks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_marks_proto_rawDescGZIP(), []int{4}
}

func (x *GetRes) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetRes) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetRes) GetTotalReports() int32 {
	if x != nil {
		return x.TotalReports
	}
	return 0
}

func (x *GetRes) GetComments() []*CommentItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_marks_proto protoreflect.FileDescriptor

const file_marks_proto_rawDesc = "" +
	"\n" +
	"\vmarks.proto\x12\x05marks\"C\n" +
	"\vCommentItem\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"x\n" +
	"\x06NewReq\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"\b\n" +
	"\x06NewRes\"B\n" +
	"\x06GetReq\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x97\x01\n" +
	"\x06GetRes\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12#\n" +
	"\rtotal_reports\x18\x03 \x01(\x05R\ftotalReports\x12.\n" +
	"\bcomments\x18\x04 \x03(\v2\x12.marks.CommentItemR\bcomments2X\n" +
	"\fMarksService\x12#\n" +
	"\x03New\x12\r.marks.NewReq\x1a\r.marks.NewRes\x12#\n" +
	"\x03Get\x12\r.marks.GetReq\x1a\r.marks.GetResB\x1fZ\x1dgenerated-marks/;marksserviceb\x06proto3"

var (
	file_marks_proto_rawDescOnce sync.Once
	file_marks_proto_rawDescData []byte
)

func file_marks_proto_rawDescGZIP() []byte {
	file_marks_proto_rawDescOnce.Do(func() {
		file_marks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marks_proto_rawDesc), len(file_marks_proto_rawDesc)))
	})
	return file_marks_proto_rawDescData
}

var file_marks_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_marks_proto_goTypes = []any{
	(*CommentItem)(nil), // 0: marks.CommentItem
	(*NewReq)(nil),      // 1: marks.NewReq
	(*NewRes)(nil),      // 2: marks.NewRes
	(*GetReq)(nil),      // 3: marks.GetReq
	(*GetRes)(nil),      // 4: marks.GetRes
}
var file_marks_proto_depIdxs = []int32{
	0, // 0: marks.GetRes.comments:type_name -> marks.CommentItem
	1, // 1: marks.MarksService.New:input_type -> marks.NewReq
	3, // 2: marks.MarksService.Get:input_type -> marks.GetReq
	2, // 3: marks.MarksService.New:output_type -> marks.NewRes
	4, // 4: marks.MarksService.Get:output_type -> marks.GetRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marks_proto_init() }
func file_marks_proto_init() {
	if File_marks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marks_proto_rawDesc), len(file_marks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marks_proto_goTypes,
		DependencyIndexes: file_marks_proto_depIdxs,
		MessageInfos:      file_marks_proto_msgTypes,
	}.Build()
	File_marks_proto = out.File
	file_marks_proto_goTypes = nil
	file_marks_proto_depIdxs = nil
}
